export const DEFAULTS = {
	apiRoot: 'https://api.telegram.org',
	parseMode: 'HTML',
	pollingTimeout: 30_000,
	connectionTimeout: 10_000,
	conflictRetries: 3,
	conflictRetryDelay: 5_000,
	typingInterval: 4_000,
	minEditInterval: 1_000,
	maxEditInterval: 3_000,
	minEditDelta: 20,
	chainOnOverflow: true,
	maxQueueDepth: 100,
	autoDownload: false,
	autoDownloadTypes: [] as readonly string[],
	autoDownloadMaxSize: 10_485_760,
	fileRetentionMs: 2_592_000_000,
	maxFileCacheBytes: 524_288_000,
	statelessMode: false,
	allowedChatIds: [] as readonly number[],
	allowedUpdates: [] as readonly string[],
} as const;
